#!/bin/sh
cd "`dirname \"$0\"`/../.."
zip -9rvy Slade-MacOSX-`date "+%Y_%m_%d_%H_%M_%S"` Slade -x .DS_Store -x *.mode1v3 -x *.pbxuser -x Slade/build/\* -x Slade/DerivedData/\* -x Slade/.deploy_image/\*
