#!/bin/sh

cd "`dirname \"$0\"`/.."

DEPLOY_IMAGE_DIR=.deploy_image

echo "Preparing directories..."
rm -r ${DEPLOY_IMAGE_DIR} 2>/dev/null
mkdir ${DEPLOY_IMAGE_DIR}
ln -s /Applications ${DEPLOY_IMAGE_DIR}/Applications

echo "Copying files..."
cp -R build/Release/Slade.app ${DEPLOY_IMAGE_DIR}
cp source/gpl-2.0.txt ${DEPLOY_IMAGE_DIR}
rm ${DEPLOY_IMAGE_DIR}/Slade.app/Contents/MacOS/slade3.log 2>/dev/null

echo "Stripping executable..."
strip ${DEPLOY_IMAGE_DIR}/Slade.app/Contents/MacOS/Slade

echo "Building image..."
hdiutil create -srcfolder ${DEPLOY_IMAGE_DIR} -volname Slade ${DEPLOY_IMAGE_DIR}/Slade.dmg
